version: '3.8'

services:
  SERVICE_NAME_PLACEHOLDER:
    image: mysql:8.0.19
    container_name: ${CONTAINER_NAME}
    ports:
      - "3321:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./${CONFIG_DIR}:/etc/mysql/conf.d
      - ./${DATA_DIR}:/var/lib/mysql
    command: --default_authentication_plugin=mysql_native_password
    networks:
      - my_network
    restart: unless-stopped

networks:
  my_network:
    external: true
